# Generated by Django 2.0.5 on 2018-05-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=14)),
                ('width', models.DecimalField(decimal_places=2, max_digits=14)),
                ('height', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.CharField(max_length=10)),
                ('image', models.URLField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('title', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('measurements', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.Measurements')),
            ],
        ),
    ]
